# Obtener base de datos de Masa salarial por sector económico

En esta libreta se trabajan los datos previamente filtrados para la Ciudad de México (para más información, ver libreta `Filtrar_CDMX.ipynb`). De ellos se obtiene un base de datos que contiene la masa salarial por tipo de puesto de trabajo:

`{'masa_sal_ta':  'Masa salarial asociada a puestos de trabajo afiliados',
'masa_sal_teu': 'Masa salarial asociada a puestos de trabajo eventuales urbanos',
'masa_sal_tec': 'Masa salarial asociada a puestos de trabajo eventuales del campo',
'masa_sal_tpu': 'Masa salarial asociada a puestos de trabajo permanentes urbanos',
'masa_sal_tpc': 'Masa salarial asociada a puestos de trabajo permanentes del campo'}`

y por sector económico `sector_economico_2_2pos` del diccionario de datos del IMSS (las definiciones de cada sector se encuentran más abajo en esta misma libreta).

Cabe mencionar que la etiqueta `masa_sal_ta` contiene la suma de las demás etiqutas de tipo de masa salarial, es decir, `masa_sal_ta` contiene el total de la masa salarial de cada sector económico.

In [9]:
# Importar bibliotecas y agregar rutas al sys.path

import os
import sys
import inspect
import numpy as np
import pandas as pd

parentdir = os.path.abspath('..')
grandparentdir=os.path.dirname(parentdir)
ggpdir=os.path.dirname(grandparentdir)

sys.path.insert(0, parentdir)
sys.path.insert(0, grandparentdir)
sys.path.insert(0, ggpdir)

In [10]:
#Obtener nombres de archivos del IMSS para CDMX (previamente filtrados en la libreta Filtrar_CDMX)
mypath=parentdir+'/IMSS_CDMX/'
asg_files= sorted([f for f in os.listdir(mypath) if f.startswith('asg')])
asg_files

['asg-2010-01_CDMX.csv',
 'asg-2010-02_CDMX.csv',
 'asg-2010-03_CDMX.csv',
 'asg-2010-04_CDMX.csv',
 'asg-2010-05_CDMX.csv',
 'asg-2010-06_CDMX.csv',
 'asg-2010-07_CDMX.csv',
 'asg-2010-08_CDMX.csv',
 'asg-2010-09_CDMX.csv',
 'asg-2010-10_CDMX.csv',
 'asg-2010-11_CDMX.csv',
 'asg-2010-12_CDMX.csv',
 'asg-2011-01_CDMX.csv',
 'asg-2011-02_CDMX.csv',
 'asg-2011-03_CDMX.csv',
 'asg-2011-04_CDMX.csv',
 'asg-2011-05_CDMX.csv',
 'asg-2011-06_CDMX.csv',
 'asg-2011-07_CDMX.csv',
 'asg-2011-08_CDMX.csv',
 'asg-2011-09_CDMX.csv',
 'asg-2011-10_CDMX.csv',
 'asg-2011-11_CDMX.csv',
 'asg-2011-12_CDMX.csv',
 'asg-2012-01_CDMX.csv',
 'asg-2012-02_CDMX.csv',
 'asg-2012-03_CDMX.csv',
 'asg-2012-04_CDMX.csv',
 'asg-2012-05_CDMX.csv',
 'asg-2012-06_CDMX.csv',
 'asg-2012-07_CDMX.csv',
 'asg-2012-08_CDMX.csv',
 'asg-2012-09_CDMX.csv',
 'asg-2012-10_CDMX.csv',
 'asg-2012-11_CDMX.csv',
 'asg-2012-12_CDMX.csv',
 'asg-2013-01_CDMX.csv',
 'asg-2013-02_CDMX.csv',
 'asg-2013-03_CDMX.csv',
 'asg-2013-04_CDMX.csv',
 'asg-2013-05_CDMX.csv',
 'asg-2013-06_CDMX.csv',
 'asg-2013-07_CDMX.csv',
 'asg-2013-08_CDMX.csv',
 'asg-2013-09_CDMX.csv',
 'asg-2013-10_CDMX.csv',
 'asg-2013-11_CDMX.csv',
 'asg-2013-12_CDMX.csv',
 'asg-2014-01_CDMX.csv',
 'asg-2014-02_CDMX.csv',
 'asg-2014-03_CDMX.csv',
 'asg-2014-04_CDMX.csv',
 'asg-2014-05_CDMX.csv',
 'asg-2014-06_CDMX.csv',
 'asg-2014-07_CDMX.csv',
 'asg-2014-08_CDMX.csv',
 'asg-2014-09_CDMX.csv',
 'asg-2014-10_CDMX.csv',
 'asg-2014-11_CDMX.csv',
 'asg-2014-12_CDMX.csv',
 'asg-2015-01_CDMX.csv',
 'asg-2015-02_CDMX.csv',
 'asg-2015-03_CDMX.csv',
 'asg-2015-04_CDMX.csv',
 'asg-2015-05_CDMX.csv',
 'asg-2015-06_CDMX.csv',
 'asg-2015-07_CDMX.csv',
 'asg-2015-08_CDMX.csv',
 'asg-2015-09_CDMX.csv',
 'asg-2015-10_CDMX.csv',
 'asg-2015-11_CDMX.csv',
 'asg-2015-12_CDMX.csv',
 'asg-2016-01_CDMX.csv',
 'asg-2016-02_CDMX.csv',
 'asg-2016-03_CDMX.csv',
 'asg-2016-04_CDMX.csv',
 'asg-2016-05_CDMX.csv',
 'asg-2016-06_CDMX.csv',
 'asg-2016-07_CDMX.csv',
 'asg-2016-08_CDMX.csv',
 'asg-2016-09_CDMX.csv',
 'asg-2016-10_CDMX.csv',
 'asg-2016-11_CDMX.csv',
 'asg-2016-12_CDMX.csv',
 'asg-2017-01_CDMX.csv',
 'asg-2017-02_CDMX.csv',
 'asg-2017-03_CDMX.csv',
 'asg-2017-04_CDMX.csv',
 'asg-2017-05_CDMX.csv',
 'asg-2017-06_CDMX.csv',
 'asg-2017-07_CDMX.csv',
 'asg-2017-08_CDMX.csv',
 'asg-2017-09_CDMX.csv',
 'asg-2017-10_CDMX.csv',
 'asg-2017-11_CDMX.csv',
 'asg-2017-12_CDMX.csv',
 'asg-2018-01_CDMX.csv',
 'asg-2018-02_CDMX.csv',
 'asg-2018-03_CDMX.csv',
 'asg-2018-04_CDMX.csv',
 'asg-2018-05_CDMX.csv',
 'asg-2018-06_CDMX.csv',
 'asg-2018-07_CDMX.csv',
 'asg-2018-08_CDMX.csv',
 'asg-2018-09_CDMX.csv',
 'asg-2018-10_CDMX.csv',
 'asg-2018-11_CDMX.csv',
 'asg-2018-12_CDMX.csv',
 'asg-2019-01_CDMX.csv',
 'asg-2019-02_CDMX.csv',
 'asg-2019-03_CDMX.csv',
 'asg-2019-04_CDMX.csv',
 'asg-2019-05_CDMX.csv',
 'asg-2019-06_CDMX.csv',
 'asg-2019-07_CDMX.csv',
 'asg-2019-08_CDMX.csv',
 'asg-2019-09_CDMX.csv',
 'asg-2019-10_CDMX.csv',
 'asg-2019-11_CDMX.csv',
 'asg-2019-12_CDMX.csv',
 'asg-2020-01_CDMX.csv',
 'asg-2020-02_CDMX.csv',
 'asg-2020-03_CDMX.csv',
 'asg-2020-04_CDMX.csv',
 'asg-2020-05_CDMX.csv',
 'asg-2020-06_CDMX.csv',
 'asg-2020-07_CDMX.csv',
 'asg-2020-08_CDMX.csv',
 'asg-2020-09_CDMX.csv',
 'asg-2020-10_CDMX.csv',
 'asg-2020-11_CDMX.csv',
 'asg-2020-12_CDMX.csv',
 'asg-2021-01_CDMX.csv',
 'asg-2021-02_CDMX.csv',
 'asg-2021-03_CDMX.csv',
 'asg-2021-04_CDMX.csv',
 'asg-2021-05_CDMX.csv',
 'asg-2021-06_CDMX.csv',
 'asg-2021-07_CDMX.csv',
 'asg-2021-08_CDMX.csv',
 'asg-2021-09_CDMX.csv',
 'asg-2021-10_CDMX.csv',
 'asg-2021-11_CDMX.csv',
 'asg-2021-12_CDMX.csv',
 'asg-2022-01_CDMX.csv',
 'asg-2022-02_CDMX.csv',
 'asg-2022-03_CDMX.csv',
 'asg-2022-04_CDMX.csv',
 'asg-2022-05_CDMX.csv',
 'asg-2022-06_CDMX.csv',
 'asg-2022-07_CDMX.csv',
 'asg-2022-08_CDMX.csv',
 'asg-2022-09_CDMX.csv',
 'asg-2022-10_CDMX.csv',
 'asg-2022-11_CDMX.csv',
 'asg-2022-12_CDMX.csv',
 'asg-2023-01_CDMX.csv',
 'asg-2023-02_CDMX.csv',
 'asg-2023-03_CDMX.csv',
 'asg-2023-04_CDMX.csv']

# Obtener las etiquetas y definiciones del sector económico 2, desde el diccionario de datos

En la siguiente celda, se muestra como se ven los datos filtrados para CDMX en un mes y año específico

In [11]:
# Leer datos previamente filtrados para CDMX

df_asg_2023_01_CDMX=pd.read_csv(mypath+'asg-2023-01_CDMX.csv',
                                low_memory=False)
df_asg_2023_01_CDMX

,Unnamed: 0,cve_delegacion,cve_subdelegacion,cve_entidad,cve_municipio,sector_economico_1,sector_economico_2,sector_economico_4,tamaño_patron,sexo,...,ta_sal,teu_sal,tec_sal,tpu_sal,tpc_sal,masa_sal_ta,masa_sal_teu,masa_sal_tec,masa_sal_tpu,masa_sal_tpc
0,0,39,11,9,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0
1,1,39,11,9,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0
2,2,39,11,9,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0
3,3,39,11,9,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0
4,4,39,11,9,NaN,NaN,NaN,NaN,NaN,1,...,0,0,0,0,0,0.00,0.0,0.0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499406,499406,40,58,9,NaN,9.0,99.0,9900.0,S3,2,...,1,0,0,1,0,1980.40,0.0,0.0,1980.40,0.0
499407,499407,40,58,9,NaN,9.0,99.0,9900.0,S3,2,...,1,0,0,1,0,2230.94,0.0,0.0,2230.94,0.0
499408,499408,40,58,9,NaN,9.0,99.0,9900.0,S3,2,...,1,0,0,1,0,2405.50,0.0,0.0,2405.50,0.0
499409,499409,40,58,9,NaN,9.0,99.0,9900.0,S3,2,...,2,0,0,2,0,4811.00,0.0,0.0,4811.00,0.0
499410,499410,40,58,9,NaN,9.0,99.0,9900.0,S3,2,...,1,0,0,1,0,1584.36,0.0,0.0,1584.36,0.0

En la siguiente celda, se muestra la hoja del diccionario de datos correspondiente al sector económico 2. Luego se muestran las etiquetas numéricas que representan a cada sector, y más adelante se imprime la definición de cada sector.

In [12]:
# Sector economico 2 de diccionario de datos

df_sec2=pd.read_excel('../row_data/diccionario_de_datos_1.xlsx',sheet_name='sector 2',skiprows=[0])
# df_rango_sal['rango_salarial'].fillna('NA',inplace=True)
df_sec2

,sector_economico_1,sector_economico_2,sector_economico_2_2pos,descripción sector_economico_2
0,0,1,1,Agricultura
1,0,2,2,Ganadería
2,0,3,3,Silvicultura
3,0,4,4,Pesca
4,0,5,5,Caza
...,...,...,...,...
57,9,1,91,"Servicios de enseñanza, investigación científi..."
58,9,2,92,"Servicios médicos, asistencia social y veterin..."
59,9,3,93,"Agrupaciones mercantiles, profesionales, cívic..."
60,9,4,94,Servicios de administración pública y segurida...
61,9,9,99,Servicios de organizaciones internacionales y ...

In [13]:
sec2=df_sec2['sector_economico_2_2pos'].values
sec2

array([ 1,  2,  3,  4,  5, 11, 12, 13, 14, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 41, 42, 50, 51, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 91, 92, 93, 94, 99])

In [14]:
for indicador in df_sec2['sector_economico_2_2pos'].values:
    print(str(indicador)+':= ',df_sec2[df_sec2['sector_economico_2_2pos']==indicador]['descripción sector_economico_2'].values[0])

1:=  Agricultura
2:=  Ganadería
3:=  Silvicultura
4:=  Pesca
5:=  Caza
11:=  Extracción  y  beneficio de carbón mineral, grafito y minerales no metálicos; excepto sal
12:=  Exploración y extracción  de  petróleo crudo y gas natural (no incluye a Pemex)
13:=  Extracción y beneficio de minerales metálicos
14:=  Explotación de sal
20:=  Fabricación de alimentos
21:=  Elaboración de bebidas
22:=  Beneficio y fabricación de productos de tabaco
23:=  Industria textil
24:=  Confección de prendas de vestir y otros artículos confeccionados con textiles y otros materiales; excepto calzado
25:=  Fabricación de  calzado e industria del cuero
26:=  Industria y productos de madera y corcho; excepto muebles
27:=  Fabricación y reparación de muebles de madera y sus partes; excepto los de metal y plástico moldeado
28:=  Industria del papel
29:=  Industrias editorial, de impresión y conexas
30:=  Industria química
31:=  Refinación del petróleo y derivados del carbón mineral (no incluye Pemex)
32:=  Fabricación de productos de hule y plástico
33:=  Fabricación de productos de minerales no metálicos;  excepto del petróleo y del carbón mineral
34:=  Industrias metálicas básicas
35:=  Fabricación de productos metálicos; excepto maquinaria y equipo
36:=  Fabricación, ensamble y reparación de maquinaria, equipo y sus partes; excepto los eléctricos
37:=  Fabricación y ensamble de maquinaria, equipos, aparatos, accesorios y artículos eléctricos, electrónicos y sus partes
38:=  Construcción, reconstrucción y ensamble de equipo de transporte y sus partes
39:=  Otras industrias manufactureras
41:=  Construcción de edificaciones y de obras de ingeniería civil
42:=  Trabajos realizados por contratistas especializados
50:=  Generación, transmisión y distribución de energía eléctrica
51:=  Captación y suministro de agua potable
61:=  Compraventa de alimentos, bebidas y productos del tabaco
62:=  Compraventa de prendas de vestir y otros artículos de uso personal
63:=  Compraventa de artículos para el hogar
64:=  Compraventa en tiendas de autoservicio y de departamentos especializados por línea de mercancías
65:=  Compraventa de gases, combustibles y lubricantes
66:=  Compraventa de materias primas, materiales y auxiliares
67:=  Compraventa de maquinaria, equipo, instrumentos, aparatos, herramientas;  sus refacciones y accesorios
68:=  Compraventa de equipo de transporte; sus refacciones y accesorios
69:=  Compraventa de inmuebles y artículos diversos
71:=  Transporte terrestre
72:=  Transporte por agua
73:=  Transporte aéreo
74:=  Servicios conexos al transporte
75:=  Servicios relacionados con el transporte en general
76:=  Comunicaciones
81:=  Servicios financieros y de seguros (bancos, financieras, compañías de seguros, etc.)
82:=  Servicios colaterales a las instituciones financieras y de seguros
83:=  Servicios relacionados con inmuebles
84:=  Servicios profesionales y técnicos
85:=  Servicios de alquiler; excepto de inmuebles
86:=  Servicios de alojamiento temporal
87:=  Preparación y servicio de alimentos y bebidas
88:=  Servicios recreativos y de esparcimiento
89:=  Servicios personales para el hogar y diversos
91:=  Servicios de enseñanza, investigación científica y difusión cultural
92:=  Servicios médicos, asistencia social y veterinarios
93:=  Agrupaciones mercantiles, profesionales, cívicas, políticas, laborales y religiosas
94:=  Servicios de administración pública y seguridad social
99:=  Servicios de organizaciones internacionales y otros organismos extraterritoriales

In [15]:
masa_sal_columns = [col for col in df_asg_2023_01_CDMX.columns if col.startswith('masa')]

masa_sal_columns

['masa_sal_ta', 'masa_sal_teu', 'masa_sal_tec', 'masa_sal_tpu', 'masa_sal_tpc']

# Seleccionar los datos donde el sector economico corresponde a un indicador específico y a los indicadores de masa salarial

En la siguiente celda se obtiene la masa salarial para los distintos tipos de puestos de trabajo, para una etiqueta del sector económico 2 en específico. Este proceso se va a iterar en cada base de datos para crear el dataframe final.

In [16]:
# Seleccionar los datos donde el sector economico corresponde a un indicador específico
# y a los indicadores de masa salarial

# masa_sal_ta:=  Masa salarial asociada a puestos de trabajo afiliados
# masa_sal_teu:=  Masa salarial asociada a puestos de trabajo eventuales urbanos
# masa_sal_tec:=  Masa salarial asociada a puestos de trabajo eventuales del campo
# masa_sal_tpu:=  Masa salarial asociada a puestos de trabajo permanentes urbanos
# masa_sal_tpc:=  Masa salarial asociada a puestos de trabajo permanentes del campo


df_masa_sal=df_asg_2023_01_CDMX[df_asg_2023_01_CDMX['sector_economico_2']==11][masa_sal_columns+['sector_economico_2']]
df_masa_sal

,masa_sal_ta,masa_sal_teu,masa_sal_tec,masa_sal_tpu,masa_sal_tpc,sector_economico_2
59,492.90,0.00,0.0,492.90,0.0,11.0
60,367.26,367.26,0.0,0.00,0.0,11.0
61,367.26,367.26,0.0,0.00,0.0,11.0
62,1101.78,1101.78,0.0,0.00,0.0,11.0
63,699.54,699.54,0.0,0.00,0.0,11.0
...,...,...,...,...,...,...
429739,301.77,0.00,0.0,301.77,0.0,11.0
429740,543.19,0.00,0.0,543.19,0.0,11.0
429741,435.34,0.00,0.0,435.34,0.0,11.0
429742,217.67,0.00,0.0,217.67,0.0,11.0
429743,1657.72,0.00,0.0,1657.72,0.0,11.0

# Loop principal

A continuación, se itera el proceso anterior para cada tipo de puesto trabajo y cada etiqueta del sector económico 2. Estos datos se guardan un dataframe en el que a cada Fecha (`aaaa-mm`) le corresponde la masa salarial por tipo de puesto de trabajo (e.g., `masa_sal_ta`) y la masa salarial por tipo de puesto de trabajo por sector económico 2 (e.g., `masa_sal_ta_1`). En cada paso del loop, se especifica la base de datos que se está trabajado y se imprime el tiempo de procesamiento. Al final, en la siguiente celda, se escribe el dataframe con nombre `'Masa_sal_Sec_2.csv'` en la carpeta creada con nombre `'IMSS_CDMX_Masa_sal_sec2'`.

In [17]:
fecha_masa_sal_sec_2=['Fecha']

for ms in masa_sal_columns:
    fecha_masa_sal_sec_2.append(ms)

for ms in masa_sal_columns:
    for s2 in sec2:
        ms_s2=ms+'_'+str(s2)
        fecha_masa_sal_sec_2.append(ms_s2)

df_fecha_ms_s2=pd.DataFrame(columns=fecha_masa_sal_sec_2)
df_fecha_ms_s2['Fecha']=[f[4:11] for f in asg_files]
df_fecha_ms_s2

,Fecha,masa_sal_ta,masa_sal_teu,masa_sal_tec,masa_sal_tpu,masa_sal_tpc,masa_sal_ta_1,masa_sal_ta_2,masa_sal_ta_3,masa_sal_ta_4,...,masa_sal_tpc_85,masa_sal_tpc_86,masa_sal_tpc_87,masa_sal_tpc_88,masa_sal_tpc_89,masa_sal_tpc_91,masa_sal_tpc_92,masa_sal_tpc_93,masa_sal_tpc_94,masa_sal_tpc_99
0,2010-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2010-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2010-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2010-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,2022-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156,2023-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157,2023-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,2023-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,2023-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
import time

t00 = time.time()

write_dir=parentdir+'/IMSS_CDMX_Masa_sal_sec2/'

if not os.path.exists(write_dir):
    os.makedirs(write_dir)

for asg_data in asg_files:
    t01 = time.time()
    
    print('Procesando:',asg_data)
#     Leer dataframe
    df_asg=pd.read_csv(mypath+asg_data,low_memory=False)
    

    
    fecha=asg_data[4:11]
    
    for s2 in sec2:
        df_s2=df_asg[df_asg['sector_economico_2']==s2]
        for ms in masa_sal_columns:
            ms_s2=ms+'_'+str(s2)
            ms_s2_total=sum(df_s2[ms].values)
#             pt_total=sum(df_asg[df_asg['rango_salarial']=='W2']['ta'])
            
            df_fecha_ms_s2.loc[df_fecha_ms_s2['Fecha']==fecha,ms_s2]=ms_s2_total
        
    for ms in masa_sal_columns:
        ms_total=sum(df_asg[ms].values)
        
        df_fecha_ms_s2.loc[df_fecha_ms_s2['Fecha']==fecha,ms]=ms_total

    
    t11 = time.time()

    total11 = t11-t01 
    
    print(total11)

t10 = time.time()


total00 = t10-t00


print('Tiempo total=',total00)

df_fecha_ms_s2

Procesando: asg-2010-01_CDMX.csv
2.143366813659668
Procesando: asg-2010-02_CDMX.csv
2.5852739810943604
Procesando: asg-2010-03_CDMX.csv
1.4126880168914795
Procesando: asg-2010-04_CDMX.csv
1.3902342319488525
Procesando: asg-2010-05_CDMX.csv
1.4968292713165283
Procesando: asg-2010-06_CDMX.csv
1.609314203262329
Procesando: asg-2010-07_CDMX.csv
1.1949150562286377
Procesando: asg-2010-08_CDMX.csv
4.5709617137908936
Procesando: asg-2010-09_CDMX.csv
1.3881890773773193
Procesando: asg-2010-10_CDMX.csv
1.2447750568389893
Procesando: asg-2010-11_CDMX.csv
1.279900312423706
Procesando: asg-2010-12_CDMX.csv
1.3866608142852783
Procesando: asg-2011-01_CDMX.csv
1.3133800029754639
Procesando: asg-2011-02_CDMX.csv
1.2178089618682861
Procesando: asg-2011-03_CDMX.csv
1.2992260456085205
Procesando: asg-2011-04_CDMX.csv
1.2443697452545166
Procesando: asg-2011-05_CDMX.csv
1.2214269638061523
Procesando: asg-2011-06_CDMX.csv
1.172239065170288
Procesando: asg-2011-07_CDMX.csv
1.3398938179016113
Procesando: asg-2011-08_CDMX.csv
1.8004639148712158
Procesando: asg-2011-09_CDMX.csv
1.360090970993042
Procesando: asg-2011-10_CDMX.csv
1.3207979202270508
Procesando: asg-2011-11_CDMX.csv
1.3142759799957275
Procesando: asg-2011-12_CDMX.csv
1.2396140098571777
Procesando: asg-2012-01_CDMX.csv
1.165550947189331
Procesando: asg-2012-02_CDMX.csv
2.117861747741699
Procesando: asg-2012-03_CDMX.csv
1.3047080039978027
Procesando: asg-2012-04_CDMX.csv
1.4825191497802734
Procesando: asg-2012-05_CDMX.csv
1.343142032623291
Procesando: asg-2012-06_CDMX.csv
1.4479639530181885
Procesando: asg-2012-07_CDMX.csv
1.3410120010375977
Procesando: asg-2012-08_CDMX.csv
1.4411671161651611
Procesando: asg-2012-09_CDMX.csv
1.4351680278778076
Procesando: asg-2012-10_CDMX.csv
1.5545578002929688
Procesando: asg-2012-11_CDMX.csv
1.3469939231872559
Procesando: asg-2012-12_CDMX.csv
2.4869918823242188
Procesando: asg-2013-01_CDMX.csv
2.2605128288269043
Procesando: asg-2013-02_CDMX.csv
1.4568700790405273
Procesando: asg-2013-03_CDMX.csv
1.551698923110962
Procesando: asg-2013-04_CDMX.csv
1.6125891208648682
Procesando: asg-2013-05_CDMX.csv
1.3541467189788818
Procesando: asg-2013-06_CDMX.csv
1.320281982421875
Procesando: asg-2013-07_CDMX.csv
1.303724765777588
Procesando: asg-2013-08_CDMX.csv
1.2940928936004639
Procesando: asg-2013-09_CDMX.csv
1.3741049766540527
Procesando: asg-2013-10_CDMX.csv
1.2955570220947266
Procesando: asg-2013-11_CDMX.csv
1.3121111392974854
Procesando: asg-2013-12_CDMX.csv
1.2545430660247803
Procesando: asg-2014-01_CDMX.csv
1.3508360385894775
Procesando: asg-2014-02_CDMX.csv
1.4959571361541748
Procesando: asg-2014-03_CDMX.csv
1.5363199710845947
Procesando: asg-2014-04_CDMX.csv
1.418154001235962
Procesando: asg-2014-05_CDMX.csv
1.3552298545837402
Procesando: asg-2014-06_CDMX.csv
1.4001109600067139
Procesando: asg-2014-07_CDMX.csv
1.453721046447754
Procesando: asg-2014-08_CDMX.csv
1.575423002243042
Procesando: asg-2014-09_CDMX.csv
1.3117969036102295
Procesando: asg-2014-10_CDMX.csv
1.3032550811767578
Procesando: asg-2014-11_CDMX.csv
1.342010259628296
Procesando: asg-2014-12_CDMX.csv
1.5553090572357178
Procesando: asg-2015-01_CDMX.csv
1.5082852840423584
Procesando: asg-2015-02_CDMX.csv
1.3871407508850098
Procesando: asg-2015-03_CDMX.csv
1.3353848457336426
Procesando: asg-2015-04_CDMX.csv
1.480729103088379
Procesando: asg-2015-05_CDMX.csv
1.455976963043213
Procesando: asg-2015-06_CDMX.csv
1.3201799392700195
Procesando: asg-2015-07_CDMX.csv
1.2965500354766846
Procesando: asg-2015-08_CDMX.csv
1.39180588722229
Procesando: asg-2015-09_CDMX.csv
1.377776861190796
Procesando: asg-2015-10_CDMX.csv
1.3714239597320557
Procesando: asg-2015-11_CDMX.csv
1.361210823059082
Procesando: asg-2015-12_CDMX.csv
1.3371131420135498
Procesando: asg-2016-01_CDMX.csv
1.4084758758544922
Procesando: asg-2016-02_CDMX.csv
1.4323067665100098
Procesando: asg-2016-03_CDMX.csv
1.5533790588378906
Procesando: asg-2016-04_CDMX.csv
1.4798049926757812
Procesando: asg-2016-05_CDMX.csv
1.5071988105773926
Procesando: asg-2016-06_CDMX.csv
1.4422321319580078
Procesando: asg-2016-07_CDMX.csv
1.558535099029541
Procesando: asg-2016-08_CDMX.csv
1.5466151237487793
Procesando: asg-2016-09_CDMX.csv
1.5086710453033447
Procesando: asg-2016-10_CDMX.csv
1.6786973476409912
Procesando: asg-2016-11_CDMX.csv
1.6087570190429688
Procesando: asg-2016-12_CDMX.csv
1.530785083770752
Procesando: asg-2017-01_CDMX.csv
1.5124828815460205
Procesando: asg-2017-02_CDMX.csv
1.7051761150360107
Procesando: asg-2017-03_CDMX.csv
1.726290225982666
Procesando: asg-2017-04_CDMX.csv
1.8218119144439697
Procesando: asg-2017-05_CDMX.csv
2.229495048522949
Procesando: asg-2017-06_CDMX.csv
1.92451810836792
Procesando: asg-2017-07_CDMX.csv
1.9432899951934814
Procesando: asg-2017-08_CDMX.csv
1.7686810493469238
Procesando: asg-2017-09_CDMX.csv
1.9257490634918213
Procesando: asg-2017-10_CDMX.csv
2.0845320224761963
Procesando: asg-2017-11_CDMX.csv
1.9281060695648193
Procesando: asg-2017-12_CDMX.csv
1.7923390865325928
Procesando: asg-2018-01_CDMX.csv
1.6978998184204102
Procesando: asg-2018-02_CDMX.csv
1.8877780437469482
Procesando: asg-2018-03_CDMX.csv
1.728015661239624
Procesando: asg-2018-04_CDMX.csv
1.7509491443634033
Procesando: asg-2018-05_CDMX.csv
1.6653509140014648
Procesando: asg-2018-06_CDMX.csv
1.6700029373168945
Procesando: asg-2018-07_CDMX.csv
1.7510778903961182
Procesando: asg-2018-08_CDMX.csv
1.763545036315918
Procesando: asg-2018-09_CDMX.csv
1.7658970355987549
Procesando: asg-2018-10_CDMX.csv
1.941838026046753
Procesando: asg-2018-11_CDMX.csv
2.031191110610962
Procesando: asg-2018-12_CDMX.csv
1.8673150539398193
Procesando: asg-2019-01_CDMX.csv
1.6975810527801514
Procesando: asg-2019-02_CDMX.csv
1.7989659309387207
Procesando: asg-2019-03_CDMX.csv
1.745920181274414
Procesando: asg-2019-04_CDMX.csv
1.9064340591430664
Procesando: asg-2019-05_CDMX.csv
1.6916251182556152
Procesando: asg-2019-06_CDMX.csv
2.1118369102478027
Procesando: asg-2019-07_CDMX.csv
1.9035680294036865
Procesando: asg-2019-08_CDMX.csv
2.2335190773010254
Procesando: asg-2019-09_CDMX.csv
1.815321922302246
Procesando: asg-2019-10_CDMX.csv
2.166558265686035
Procesando: asg-2019-11_CDMX.csv
3.8459889888763428
Procesando: asg-2019-12_CDMX.csv
3.307711124420166
Procesando: asg-2020-01_CDMX.csv
4.885164022445679
Procesando: asg-2020-02_CDMX.csv
2.4656641483306885
Procesando: asg-2020-03_CDMX.csv
1.9688730239868164
Procesando: asg-2020-04_CDMX.csv
1.7953991889953613
Procesando: asg-2020-05_CDMX.csv
1.7816951274871826
Procesando: asg-2020-06_CDMX.csv
1.9382131099700928
Procesando: asg-2020-07_CDMX.csv
1.7763192653656006
Procesando: asg-2020-08_CDMX.csv
2.070341110229492
Procesando: asg-2020-09_CDMX.csv
2.866745948791504
Procesando: asg-2020-10_CDMX.csv
2.0936050415039062
Procesando: asg-2020-11_CDMX.csv
2.1387040615081787
Procesando: asg-2020-12_CDMX.csv
2.0216939449310303
Procesando: asg-2021-01_CDMX.csv
2.2822518348693848
Procesando: asg-2021-02_CDMX.csv
2.077742099761963
Procesando: asg-2021-03_CDMX.csv
5.772686004638672
Procesando: asg-2021-04_CDMX.csv
4.54879903793335
Procesando: asg-2021-05_CDMX.csv
3.0457892417907715
Procesando: asg-2021-06_CDMX.csv
2.0913307666778564
Procesando: asg-2021-07_CDMX.csv
1.9868719577789307
Procesando: asg-2021-08_CDMX.csv
6.425551891326904
Procesando: asg-2021-09_CDMX.csv
2.075176954269409
Procesando: asg-2021-10_CDMX.csv
4.075906038284302
Procesando: asg-2021-11_CDMX.csv
3.450435161590576
Procesando: asg-2021-12_CDMX.csv
3.9940860271453857
Procesando: asg-2022-01_CDMX.csv
7.343169927597046
Procesando: asg-2022-02_CDMX.csv
2.941624879837036
Procesando: asg-2022-03_CDMX.csv
2.117569923400879
Procesando: asg-2022-04_CDMX.csv
1.8743720054626465
Procesando: asg-2022-05_CDMX.csv
2.173661231994629
Procesando: asg-2022-06_CDMX.csv
2.9924678802490234
Procesando: asg-2022-07_CDMX.csv
2.73311185836792
Procesando: asg-2022-08_CDMX.csv
2.8384060859680176
Procesando: asg-2022-09_CDMX.csv
5.999359846115112
Procesando: asg-2022-10_CDMX.csv
3.93772292137146
Procesando: asg-2022-11_CDMX.csv
2.995897054672241
Procesando: asg-2022-12_CDMX.csv
2.030461072921753
Procesando: asg-2023-01_CDMX.csv
1.9463417530059814
Procesando: asg-2023-02_CDMX.csv
2.092496871948242
Procesando: asg-2023-03_CDMX.csv
1.8313069343566895
Procesando: asg-2023-04_CDMX.csv

4.290406227111816
Tiempo total= 316.0705637931824

,Fecha,masa_sal_ta,masa_sal_teu,masa_sal_tec,masa_sal_tpu,masa_sal_tpc,masa_sal_ta_1,masa_sal_ta_2,masa_sal_ta_3,masa_sal_ta_4,...,masa_sal_tpc_85,masa_sal_tpc_86,masa_sal_tpc_87,masa_sal_tpc_88,masa_sal_tpc_89,masa_sal_tpc_91,masa_sal_tpc_92,masa_sal_tpc_93,masa_sal_tpc_94,masa_sal_tpc_99
0,2010-01,795708666.799878,62274037.740002,0.0,733434629.05993,0.0,165869.83,218018.56,5677.67,2695.38,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2010-02,799290269.619883,63216220.600001,0.0,736074049.019928,0.0,171166.49,254836.64,5547.32,3000.62,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2010-03,794064878.509875,65200137.260001,0.0,728864741.249944,0.0,169638.7,258697.97,5886.37,3195.62,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2010-04,797416477.279865,65627314.580002,0.0,731789162.699917,0.0,172838.26,272625.1,5886.37,3465.56,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2010-05,810774358.689839,67215692.950002,0.0,743558665.739866,0.0,173027.61,295062.58,5760.35,3530.56,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,2022-12,2091462225.009816,200112151.930029,200.0,1891344446.789781,5426.29,967811.51,2152676.25,9825.14,41799.33,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
156,2023-01,2212190132.400419,211398639.479976,217.67,2000785034.960322,6240.29,913801.14,1971717.96,8382.51,54368.88,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157,2023-02,2253413930.04037,217769245.859977,217.67,2035638226.220287,6240.29,906440.72,1962962.66,9027.57,54482.39,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
158,2023-03,2276352018.290335,224724555.809977,217.67,2051619758.240247,7486.57,874848.66,2013708.49,8168.78,42658.24,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159,2023-04,2289243778.500325,228229142.699971,217.67,2061007557.950231,6860.18,866847.16,2071795.59,7973.44,45647.75,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
df_fecha_ms_s2.to_csv('../IMSS_CDMX_Masa_Salarial/Masa_sal_Sec_2.csv')